on:
    push:
      branches:
        - main
  
jobs:
    build-apk:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/cache@v3
          with:
            path: ~/.pub-cache
            key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.yaml') }}
            restore-keys: |
              ${{ runner.os }}-pub-
        - name: Checkout Repository
          uses: actions/checkout@v2
        
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.13.4'
        
        - name: Build APK
          run: flutter build apk
        
        - name: Upload APK
          uses: actions/upload-artifact@v2
          with:
            name: app-apk
            path: build/app/outputs/flutter-apk/app-release.apk
  