on:
    push:
      branches:
        - main
  
jobs:
    build-apk:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        - uses: dart-lang/setup-dart@v1  # Fetch the setup-dart action
          with:
            sdk: '>=3.4.0 <4.0.0' 
        
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.13.4'
        
        - name: Build APK
          run: flutter build apk
        
        - name: Upload APK
          uses: actions/upload-artifact@v2
          with:
            name: app-apk
            path: build/app/outputs/flutter-apk/app-release.apk
  