on:
    push:
      branches:
        - main
  
jobs:
    build-apk:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: 'stable'
        
        - name: Build APK
          run: flutter build apk
        
        - name: Upload APK
          uses: actions/upload-artifact@v2
          with:
            name: app-apk
            path: build/app/outputs/flutter-apk/app-release.apk
  