name: Flutter Android Build

on:
    push:
      branches:
        - main
        
jobs:
    build-apk:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set environment variables
          env:
            AZURE_FUNCTION_CODE: ${{ secrets.AZURE_FUNCTION_CODE }}
          run: echo " name=AZURE_FUNCTION_CODE is $AZURE_FUNCTION_CODE"

        - uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'
        
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: 'stable'

        - run: flutter pub get
        - name: Build APK
          run: flutter build apk --release --split-per-abi
        
        - name: Push to Releases
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/apk/release/*" 
            tag: v0.3.2
            token: ${{ secrets.TOKEN }}

