# on:
#     push:
#       branches:
#         - main
  
# jobs:
#     build-apk:
#       runs-on: ubuntu-latest
#       steps:
#         - name: Checkout Repository
#           uses: actions/checkout@v2
        
#         - name: Setup Flutter
#           uses: subosito/flutter-action@v2
#           with:
#             flutter-version: '3.13.4'

#         - uses: actions/checkout@v4
#         - uses: dart-lang/setup-dart@v1
  
#         # - run: dart pub get
#         # - run: dart format --output=none --set-exit-if-changed .
#         # - run: dart analyze
#         # - run: dart test 
        
#         - name: Build APK
#           run: flutter build apk
        
#         - name: Upload APK
#           uses: actions/upload-artifact@v2
#           with:
#             name: app-apk
#             path: build/app/outputs/flutter-apk/app-release.apk


name: Flutter Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          java-package: jdk
          check-latest: false
          # java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - run: flutter analyze

      - run: flutter build apk --release

      - uses: actions/upload-artifact@v3
        with:
          name: android-release-apk
          path: build/app/outputs/apk/release/app-release.apk
